# Generated by Django 3.0.5 on 2020-04-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_feddbacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feddbacks',
            new_name='Feedbacks',
        ),
    ]
